functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность залогиниться на сайте*
  - Пользователь должен иметь возможность создать игру
  - В игре можно выбрать уровень сложности
  - Пользователь может отправить запрос на игру любому игроку, боту, или другу'
  - Пользователь может принять запрос на игру от любого игрока или друга, либо
    отклонить запрос
  - В игру можно играть с любым человеком, с ботом или другом'
  - В игре можно установить таймер
  - В игре можно выбрать задание
  - Задачи должны быть даны на двух языках — русском и английском
  - Другие пользователи могут следить за ходом игры онлайн
  - В игре есть чат, в котором общаются зарегистрированные пользователи'
  - Завершенная игра доступна в записи. Редактор для ввода кода выглядит как
    проигрыватель
  - Пользователи получают очки, на основе которых строится рейтинг за неделю,
    месяц и за все время
  - Текст задания нельзя скопировать
  - Пользователь может отправить сообщение любому игроку онлайн
  
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Важно, чтобы сайт мог обрабатывать большое количество трафика'
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
  
implicit:
  - На сайт нужно добавить возможность выбора языка (рус, eng)'
  - Раздел «Online players» перенести снизу в шапку страницы, сделав кнопку с
    ко-вом игроков Online кликабельной. При нажатии на кнопку выпадает список
    онлайн игроков и возможность отправить им сообщение или вызов на битву. (В
    качестве примера взять кнопку с именем пользователя)

